apiVersion: apps/v1
kind: Deployment
metadata:
  name: webapp
  labels:
    app: hellok8s
spec:
  replicas: 2
  selector:
    matchLabels:
      service: webapp
  template:
    metadata:
      labels:
        app: hellok8s
        service: webapp
    spec:
      containers:
      - name: webapp
        image: mojo106/dotnet-webapp-docker:latest
        imagePullPolicy: IfNotPresent
        ports:
          - containerPort: 80
            protocol: TCP
        # resources:
        #   limits:
        #     memory: "128Mi" #128 MB
        #     cpu: "200m" #200 millicpu (.2 cpu or 20% of the cpu)

apiVersion: v1
kind: Service
metadata:
  name: webapp
  labels:
    app: hellok8s
    service: webapp
spec:
  type: LoadBalancer
  ports:
    - port: 80
      targetPort: 80
      protocol: TCP
  selector:
    service: webapp